In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
from dotenv import load_dotenv
project_root = os.path.abspath("..")
sys.path.insert(0, project_root)

In [9]:
load_dotenv()
BASE_PATH = os.getenv("BASE_PATH")
df = pd.read_parquet(f"{BASE_PATH}/data/processed/clean_delivery_time.parquet")
df.head()

,Distance_m,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,7930.0,Windy,Low,Afternoon,Scooter,12,1,43
1,16420.0,Clear,Medium,Evening,Bike,20,2,84
2,9520.0,Foggy,Low,Night,Scooter,28,1,59
3,7440.0,Rainy,Medium,Afternoon,Scooter,5,1,37
4,19030.0,Clear,Low,Morning,Bike,16,5,68

In [10]:
traffic_map = {'Low': 0, 'Medium': 1, 'High': 2}
df['Traffic_Level'] = df['Traffic_Level'].map(traffic_map)

In [13]:
df['Traffic_Level'].value_counts()

Traffic_Level
1    420
0    383
2    197
Name: count, dtype: int64

In [14]:
df = pd.get_dummies(df, columns=['Weather', 'Time_of_Day', 'Vehicle_Type'], drop_first=True)

In [15]:
df.head()

,Distance_m,Traffic_Level,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min,Weather_Foggy,Weather_Rainy,Weather_Snowy,Weather_Windy,Time_of_Day_Evening,Time_of_Day_Morning,Time_of_Day_Night,Vehicle_Type_Car,Vehicle_Type_Scooter
0,7930.0,0,12,1,43,False,False,False,True,False,False,False,False,True
1,16420.0,1,20,2,84,False,False,False,False,True,False,False,False,False
2,9520.0,0,28,1,59,True,False,False,False,False,False,True,False,True
3,7440.0,1,5,1,37,False,True,False,False,False,False,False,False,True
4,19030.0,0,16,5,68,False,False,False,False,False,True,False,False,False

In [16]:
df.to_parquet(f"{BASE_PATH}/data/processed/feature_engineering_clean_delivery_time.parquet")